import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Session from "@/components/Session";
import Theme from "@/components/Theme";
import Recoil from "@/components/Recoil";

const inter = Inter({ 
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Session>
      <Recoil>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <Theme>
            {children}
          </Theme>
        </body>
      </html>
      </Recoil>
    </Session>
  );
}
