import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Session from "@/components/Session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Session>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </Session>
  );
}
